/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package tndown.tndir.simplevd.vdwload.gitvideo.tags;

import tndown.tndir.simplevd.vdwload.gitvideo.PatternsHolder;

public class bs extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"sekundi", "sekunde", "sekundu"},
            MINUTES  /**/ = {"minuta", "minute", "minutu"},
            HOURS    /**/ = {"h", "sat", "sata", "sati"},
            DAYS     /**/ = {"dan", "dana"},
            WEEKS    /**/ = {"sedm."},
            MONTHS   /**/ = {"mj.", "mjesec", "mjeseca", "mjeseci"},
            YEARS    /**/ = {"godina", "godine", "godinu"};

    private static final bs INSTANCE = new bs();

    public static bs getInstance() {
        return INSTANCE;
    }

    private bs() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}