/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package tndown.tndir.simplevd.vdwload.gitvideo.tags;

import tndown.tndir.simplevd.vdwload.gitvideo.PatternsHolder;

public class ne extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"सेकेन्ड"},
            MINUTES  /**/ = {"मिनेट"},
            HOURS    /**/ = {"घन्टा"},
            DAYS     /**/ = {"दिन"},
            WEEKS    /**/ = {"हप्ता"},
            MONTHS   /**/ = {"महिना"},
            YEARS    /**/ = {"वर्ष"};

    private static final ne INSTANCE = new ne();

    public static ne getInstance() {
        return INSTANCE;
    }

    private ne() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}