/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package tevd.nbapp.vide.downl.gitvideo.tags;

import tevd.nbapp.vide.downl.gitvideo.PatternsHolder;

public class mk extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"секунда", "секунди"},
            MINUTES  /**/ = {"минута", "минути"},
            HOURS    /**/ = {"час", "часа"},
            DAYS     /**/ = {"ден", "дена"},
            WEEKS    /**/ = {"недела", "недели"},
            MONTHS   /**/ = {"месец", "месеци"},
            YEARS    /**/ = {"година", "години"};

    private static final mk INSTANCE = new mk();

    public static mk getInstance() {
        return INSTANCE;
    }

    private mk() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}