/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package com.ppd.ersan.video.timeago.patterns;

import com.ppd.ersan.video.timeago.PatternsHolder;

public class vi extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"giây"},
            MINUTES  /**/ = {"phút"},
            HOURS    /**/ = {"giờ", "tiếng"},
            DAYS     /**/ = {"ngày"},
            WEEKS    /**/ = {"tuần"},
            MONTHS   /**/ = {"tháng"},
            YEARS    /**/ = {"năm"};

    private static final vi INSTANCE = new vi();

    public static vi getInstance() {
        return INSTANCE;
    }

    private vi() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}