/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package music.player.extract.downd.tago.pterns;

import music.player.extract.downd.tago.PatternsHolder;

public class nl extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"seconde", "seconden"},
            MINUTES  /**/ = {"minuten", "minuut"},
            HOURS    /**/ = {"uur"},
            DAYS     /**/ = {"dag", "dagen"},
            WEEKS    /**/ = {"week", "weken"},
            MONTHS   /**/ = {"maand", "maanden"},
            YEARS    /**/ = {"jaar"};

    private static final nl INSTANCE = new nl();

    public static nl getInstance() {
        return INSTANCE;
    }

    private nl() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}