/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package music.player.extract.downd.tago.pterns;

import music.player.extract.downd.tago.PatternsHolder;

public class ur extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"سیکنڈ", "سیکنڈز"},
            MINUTES  /**/ = {"منٹ", "منٹس"},
            HOURS    /**/ = {"گھنٹہ", "گھنٹے"},
            DAYS     /**/ = {"دن"},
            WEEKS    /**/ = {"ہفتہ", "ہفتے"},
            MONTHS   /**/ = {"ماہ"},
            YEARS    /**/ = {"سال"};

    private static final ur INSTANCE = new ur();

    public static ur getInstance() {
        return INSTANCE;
    }

    private ur() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}