/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package vthirtylib.second.third.downdir.mvideo.tags;

import vthirtylib.second.third.downdir.mvideo.PatternsHolder;

public class en_GB extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"second", "seconds"},
            MINUTES  /**/ = {"minute", "minutes"},
            HOURS    /**/ = {"hour", "hours"},
            DAYS     /**/ = {"day", "days"},
            WEEKS    /**/ = {"week", "weeks"},
            MONTHS   /**/ = {"month", "months"},
            YEARS    /**/ = {"year", "years"};

    private static final en_GB INSTANCE = new en_GB();

    public static en_GB getInstance() {
        return INSTANCE;
    }

    private en_GB() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}