/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package vthirtylib.second.third.downdir.mvideo.tags;

import vthirtylib.second.third.downdir.mvideo.PatternsHolder;

public class ka extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"წამის"},
            MINUTES  /**/ = {"წუთის"},
            HOURS    /**/ = {"საათის"},
            DAYS     /**/ = {"დღის"},
            WEEKS    /**/ = {"კვირის"},
            MONTHS   /**/ = {"თვის"},
            YEARS    /**/ = {"წლის"};

    private static final ka INSTANCE = new ka();

    public static ka getInstance() {
        return INSTANCE;
    }

    private ka() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}